on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/compose-action@v2
      with:
        version: '1.29.2'  # Use the version you need

    - name: Run Tests
      run: |
        docker-compose exec app pytest